version: "3.8"
services:
  database:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  backend:
    user: ${DOCKER_UID}
    ports:
      - ${API_PORT}:3000
    build:
      context: ../backend
      dockerfile: ../docker/backend.Dockerfile
      args:
        UID: ${DOCKER_UID}
        UPASSWORD: ${DOCKER_UPASSWORD}
        UNAME: ${DOCKER_UNAME}
        PROJECT: ${PROJECT}
        DB_USER: postgres
        DB_HOST: database
        DB_PASSWORD: postgres
    environment:
      CLIENT_IP: ${CLIENT_IP}
      CLIENT_PORT: ${CLIENT_PORT}
      DB_USER: postgres
      DB_HOST: database
      DB_PASSWORD: postgres
    depends_on:
      - database
  frontend:
    ports:
      - ${CLIENT_PORT}:3000
    user: ${DOCKER_UID}      
    build:
      context: ../frontend
      dockerfile: ../docker/frontend.Dockerfile
      args:
        UID: ${DOCKER_UID}
        UPASSWORD: ${DOCKER_UPASSWORD}        
        UNAME: ${DOCKER_UNAME}
        PROJECT: ${PROJECT}
    environment:
      REACT_APP_SERVER_IP: ${SERVER_IP}
      REACT_APP_API_PORT: ${API_PORT}
